//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeluxeOM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement
    {
        public string ChangeStatus { get; set; }
        public string ChangedFields { get; set; }
        public string ChangeContext { get; set; }
        public string LocalTitle { get; set; }
        public string GlobalTitle { get; set; }
        public string TitleContentType { get; set; }
        public int Country { get; set; }
        public int Language { get; set; }
        public string LanguageType { get; set; }
        public string SalesChannel { get; set; }
        public string Format { get; set; }
        public string HDR { get; set; }
        public System.DateTime ClientStart { get; set; }
        public System.DateTime ClientEnd { get; set; }
        public string ClientAvailStatus { get; set; }
        public string ECAvailable { get; set; }
        public Nullable<System.DateTime> SuppressionEndDate { get; set; }
        public string TitleCategory { get; set; }
        public string PriceType { get; set; }
        public string PriceTier { get; set; }
        public string WSCost { get; set; }
        public string StorefrontCurrency { get; set; }
        public Nullable<System.DateTime> LocalDataTheatricalReleaseDt { get; set; }
        public Nullable<System.DateTime> LocalDVDReleaseDate { get; set; }
        public string LocalDataRating { get; set; }
        public string RatingReason { get; set; }
        public string LocalDataDVS { get; set; }
        public string TitleMPM { get; set; }
        public string TitleVideoVersion { get; set; }
        public string LocalEditRequired { get; set; }
        public string TitleAbstractEIDR { get; set; }
        public string LocalDataEditEIDR { get; set; }
        public string LocalDataUVPublishDate { get; set; }
        public string LocalDataALID { get; set; }
        public string LocalDataCID { get; set; }
        public string ClientAvailID { get; set; }
        public string AccountName { get; set; }
        public int Company { get; set; }
        public string AvailNotes { get; set; }
        public string ChannelFormat { get; set; }
    }
}
