//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeluxeOM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTPConfig
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Host { get; set; }
        public string FtpDirectory { get; set; }
        public string FileName { get; set; }
        public string DownloadTo { get; set; }
        public Nullable<bool> KeepOriginal { get; set; }
        public Nullable<bool> OverWriteExisting { get; set; }
        public Nullable<int> Port { get; set; }
        public Nullable<bool> EnableSSL { get; set; }
        public string Environment { get; set; }
        public string FtpArchivalDirectory { get; set; }
    }
}
