//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeluxeOM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB
    {
        public int Id { get; set; }
        public string JobType { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Description { get; set; }
        public string TriggeredBy { get; set; }
        public string FileName { get; set; }
    }
}
