//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeluxeOM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderGridModel
    {
        public int Id { get; set; }
        public int VIDId { get; set; }
        public int TerritoryLanguageId { get; set; }
        public int LanguageTypeId { get; set; }
        public string Vendor { get; set; }
        public Nullable<int> FileTypeId { get; set; }
        public string RequestNumber { get; set; }
        public string MPO { get; set; }
        public string HALID { get; set; }
        public Nullable<int> OrderStatusId { get; set; }
        public Nullable<System.DateTime> OrderRequestDate { get; set; }
        public Nullable<System.DateTime> DeliveryDueDate { get; set; }
        public Nullable<System.DateTime> ActualDeliveryDate { get; set; }
        public Nullable<System.DateTime> FirstStartDate { get; set; }
        public Nullable<System.DateTime> GreenlightDueDate { get; set; }
        public Nullable<System.DateTime> GreenlightValidatedbyDMDM { get; set; }
        public Nullable<System.DateTime> GreenlightSenttoPackaging { get; set; }
        public string Notes { get; set; }
        public int CustomerId { get; set; }
    }
}
