//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeluxeOM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderGrid
    {
        public int Id { get; set; }
        public int AnnouncementId { get; set; }
        public string VendorId { get; set; }
        public string LanguageType { get; set; }
        public string Category { get; set; }
        public string ESTUPC { get; set; }
        public string IVODUPC { get; set; }
        public string FileType { get; set; }
        public string RequestNumber { get; set; }
        public string MPO { get; set; }
        public string HALID { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<System.DateTime> OrderRequestDate { get; set; }
        public Nullable<System.DateTime> DeliveryDueDate { get; set; }
        public Nullable<System.DateTime> ActualDeliveryDate { get; set; }
        public Nullable<System.DateTime> GreenlightDueDate { get; set; }
        public Nullable<System.DateTime> GreenlightValidatedbyDMDM { get; set; }
        public Nullable<System.DateTime> GreenlightSenttoPackaging { get; set; }
        public string Notes { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> JObId { get; set; }
        public Nullable<int> LockedBy { get; set; }
        public Nullable<System.DateTime> LockedOn { get; set; }
        public Nullable<bool> IsLocked { get; set; }
    }
}
