//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeluxeOM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordResetEntity
    {
        public int PasswordResetId { get; set; }
        public int UserId { get; set; }
        public string Email { get; set; }
        public string Token { get; set; }
        public System.DateTime ExpireDateTime { get; set; }
    
        public virtual UserEntity User { get; set; }
    }
}
