//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeluxeOM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PipelineOrderModel
    {
        public int Id { get; set; }
        public string HALOrderID { get; set; }
        public string TitleName { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string OrderStatus { get; set; }
        public string ContractDueDate { get; set; }
        public string TargetDueDate { get; set; }
        public string PurchaseOrder { get; set; }
        public string WorkOrder { get; set; }
        public string CableLabsAssetID { get; set; }
        public string CableLabsPackageAssetID { get; set; }
        public string Workflow { get; set; }
        public string GatorPO { get; set; }
        public string WBAnnouncement { get; set; }
        public string IngredientAssetType { get; set; }
        public Nullable<int> IngredientLanguageId { get; set; }
        public string IngredientStatus { get; set; }
    }
}
