//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeluxeOM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceReportModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string VendorId { get; set; }
        public string AppleId { get; set; }
        public string Territory { get; set; }
        public string LiveVODHD { get; set; }
        public string LiveVODSD { get; set; }
        public string LiveESTHD { get; set; }
        public string LiveESTSD { get; set; }
        public Nullable<System.DateTime> PreOrderDate { get; set; }
        public Nullable<bool> ClearedforSaleEST { get; set; }
        public Nullable<bool> EnableESTHD { get; set; }
        public Nullable<System.DateTime> ESTStartDate { get; set; }
        public Nullable<bool> ClearedforVOD { get; set; }
        public Nullable<bool> EnableVODHD { get; set; }
        public Nullable<System.DateTime> AvailForVOD { get; set; }
        public Nullable<int> CustomerId { get; set; }
    }
}
