//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeluxeOM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class QCReportModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string AppleId { get; set; }
        public string VendorId { get; set; }
        public string ImportedDate { get; set; }
        public string ComponentType { get; set; }
        public string LocaleCode { get; set; }
        public string Territory { get; set; }
        public string ComponentQuality { get; set; }
        public string QAStatus { get; set; }
        public int CustomerId { get; set; }
    }
}
