//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeluxeOM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Territory
    {
        public int Id { get; set; }
        public string WBTerritory { get; set; }
        public string CountryCode { get; set; }
        public string AppleTerritory { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string PACKAGE { get; set; }
        public string GROUP { get; set; }
    }
}
