//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeluxeOM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerritoryLanguage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TerritoryLanguage()
        {
            this.AnnouncementGrids = new HashSet<AnnouncementGrid>();
        }
    
        public int TerritoryLanguageId { get; set; }
        public int TerritoryId { get; set; }
        public int LanguageSeq { get; set; }
        public int LanguageId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnnouncementGrid> AnnouncementGrids { get; set; }
        public virtual Language Language { get; set; }
        public virtual OrderGrid OrderGrid { get; set; }
        public virtual Territory Territory { get; set; }
    }
}
