//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeluxeOM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPasswordModel
    {
        public int UserPasswordId { get; set; }
        public int UserId { get; set; }
        public string Password { get; set; }
        public System.DateTime PasswordDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual UserModel User { get; set; }
    }
}
