//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeluxeOM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class VID_DETAILSModel
    {
        public int Id { get; set; }
        public Nullable<int> VidId { get; set; }
        public Nullable<int> VIDStatus { get; set; }
        public Nullable<bool> Bundle { get; set; }
        public Nullable<bool> Extras { get; set; }
        public string MPM { get; set; }
        public string AppleId { get; set; }
        public string VendorId { get; set; }
        public Nullable<int> TitleCategoryId { get; set; }
    }
}
