//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeluxeOM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIDKeyRelation
    {
        public int Id { get; set; }
        public int VidId { get; set; }
        public string TitleId { get; set; }
        public string AppleID { get; set; }
        public string VendorID { get; set; }
    }
}
