CREATE TABLE [dbo].[Announcements](
	[ChangeStatus] [nvarchar](50) NOT NULL,
	[ChangedFields] [nvarchar](500) NULL,
	[ChangeContext] [nvarchar](256) NULL,
	[LocalTitle] [nvarchar](256) NOT NULL,
	[GlobalTitle] [nvarchar](256) NOT NULL,
	[TitleContentType] [nvarchar](50) NOT NULL,
	[Country] [int] NOT NULL,
	[Language] [int] NOT NULL,
	[LanguageType] [nvarchar](50) NOT NULL,
	[SalesChannel] [nvarchar](50) NOT NULL,
	[Format] [nvarchar](50) NOT NULL,
	[HDR] [nvarchar](50) NULL,
	[ClientStart] [datetime] NOT NULL,
	[ClientEnd] [datetime] NOT NULL,
	[ClientAvailStatus] [nvarchar](50) NOT NULL,
	[ECAvailable] [nvarchar](50) NULL,
	[SuppressionEndDate] [datetime] NULL,
	[TitleCategory] [nvarchar](500) NOT NULL,
	[PriceType] [nvarchar](20) NOT NULL,
	[PriceTier] [nvarchar](256) NULL,
	[WSCost] [nvarchar](10) NULL,
	[StorefrontCurrency] [nvarchar](3) NOT NULL,
	[LocalDataTheatricalReleaseDt] [datetime] NULL,
	[LocalDVDReleaseDate] [datetime] NULL,
	[LocalDataRating] [nvarchar](100) NULL,
	[RatingReason] [nvarchar](256) NULL,
	[LocalDataDVS] [nvarchar](256) NOT NULL,
	[TitleMPM] [nvarchar](10) NOT NULL,
	[TitleVideoVersion] [nvarchar](20) NOT NULL,
	[LocalEditRequired] [nvarchar](20) NULL,
	[TitleAbstractEIDR] [nvarchar](256) NULL,
	[LocalDataEditEIDR] [nvarchar](256) NULL,
	[LocalDataUVPublishDate] [nvarchar](256) NULL,
	[LocalDataALID] [nvarchar](256) NULL,
	[LocalDataCID] [nvarchar](256) NULL,
	[ClientAvailID] [nvarchar](25) NOT NULL,
	[AccountName] [nvarchar](500) NOT NULL,
	[Company] [int] NOT NULL,
	[AvailNotes] [nvarchar](500) NULL,
	[ChannelFormat] [nvarchar](100) NULL
) ON [PRIMARY]



--Staging Table


CREATE TABLE [Announcements_STAGING]
(
	[ChangeStatus] [nvarchar](256) NULL,
	[ChangedFields] [nvarchar](256) NULL,
	[ChangeContext] [nvarchar](256) NULL,
	[LocalTitleLocalTitle] [nvarchar](256) NULL,
	[GlobalTitle] [nvarchar](256) NULL,
	[TitleContentType] [nvarchar](256) NULL,
	[Country] [nvarchar](256) NULL,
	[Language] [nvarchar](256) NULL,
	[LanguageType] [nvarchar](256) NULL,
	[SalesChannel] [nvarchar](256) NULL,
	[Format] [nvarchar](256) NULL,
	[HDR] [nvarchar](256) NULL,
	[ClientStart] [nvarchar](256) NULL,
	[ClientEnd] [nvarchar](256) NULL,
	[ClientAvailStatus] [nvarchar](256) NULL,
	[ECAvailable] [nvarchar](256) NULL,
	[SuppressionEndDate] [nvarchar](256) NULL,
	[TitleCategory] [nvarchar](256) NULL,
	[PriceType] [nvarchar](256) NULL,
	[PriceTier] [nvarchar](256) NULL,
	[WSCost] [nvarchar](256) NULL,
	[StorefrontCurrency] [nvarchar](256) NULL,
	[LocalDataTheatricalReleaseDt] [nvarchar](256) NULL,
	[LocalDVDReleaseDate] [nvarchar](256) NULL,
	[LocalDataRating] [nvarchar](256) NULL,
	[RatingReason] [nvarchar](256) NULL,
	[LocalDataDVS] [nvarchar](256) NULL,
	[TitleMPM] [nvarchar](256) NULL,
	[TitleVideoVersion] [nvarchar](256) NULL,
	[LocalEditRequired] [nvarchar](256) NULL,
	[TitleAbstractEIDR] [nvarchar](256) NULL,
	[LocalDataEditEIDR] [nvarchar](256) NULL,
	[LocalDataUVPublishDate] [nvarchar](256) NULL,
	[LocalDataALID] [nvarchar](256) NULL,
	[LocalDataCID] [nvarchar](256) NULL,
	[ClientAvailID] [nvarchar](256) NULL,
	[AccountName] [nvarchar](256) NULL,
	[Company] [nvarchar](256) NULL,
	[AvailNotes] [nvarchar](256) NULL
) ON [PRIMARY]

GO

